assets:
  js:
    - bundles/os2displaytemplateextension/assets/libs/quill.min.js
    - bundles/os2displaytemplateextension/assets/libs/ng-quill.min.js
  css:
    - bundles/os2displaytemplateextension/css/quill.core.css
    - bundles/os2displaytemplateextension/css/quill.snow.css
    - bundles/os2displaytemplateextension/assets/build/os2displaytemplateextension.min.css
  js_prod_assets:
    - bundles/os2displaytemplateextension/assets/libs/quill.min.js
    - bundles/os2displaytemplateextension/assets/libs/ng-quill.min.js
  js_prod:
    - bundles/os2displaytemplateextension/assets/build/os2displaytemplateextension.min.js

modules:
  templateExtensionModule:
    files:
      - bundles/os2displaytemplateextension/apps/templateExtensionModule/module.js
      - bundles/os2displaytemplateextension/apps/templateExtensionModule/itk-rich-text.js
      - bundles/os2displaytemplateextension/apps/templateExtensionModule/itk-text-array.js
      - bundles/os2displaytemplateextension/apps/templateExtensionModule/itk-color-picker.js
      - bundles/os2displaytemplateextension/apps/templateExtensionModule/itk-media-picker.js

apps:
  ikApp:
    dependencies:
      - templateExtensionModule
